/**
 * Hand-curated 1950-1957 standards. Billboard's Hot 100 didn't launch until
 * August 1958, so these songs have no source chart data — buildTrackCatalog.mjs
 * merges them into the "1950s" bucket without a `popularity` score.
 */
export const MANUAL_PRE_1958_TRACKS = [
  { title: "Sentimental Me", artist: "The Ames Brothers", releaseYear: 1950 },
  { title: "Chattanoogie Shoe Shine Boy", artist: "Red Foley", releaseYear: 1950 },
  { title: "Music! Music! Music!", artist: "Teresa Brewer", releaseYear: 1950 },
  { title: "The Third Man Theme", artist: "Anton Karas", releaseYear: 1950 },
  { title: "Sam's Song", artist: "Gary Crosby and Friend", releaseYear: 1950 },
  { title: "Simple Melody", artist: "Gary Crosby and Friend", releaseYear: 1950 },
  { title: "Bonaparte's Retreat", artist: "Kay Starr", releaseYear: 1950 },
  { title: "Can Anyone Explain?", artist: "The Ames Brothers", releaseYear: 1950 },
  { title: "Nevertheless", artist: "The Mills Brothers", releaseYear: 1950 },
  { title: "Thinking of You", artist: "Don Cherry", releaseYear: 1950 },
  { title: "I'll Never Be Free", artist: "Tennessee Ernie Ford and Kay Starr", releaseYear: 1950 },
  { title: "Daddy's Little Girl", artist: "The Mills Brothers", releaseYear: 1950 },
  { title: "Mockin' Bird Hill", artist: "Patti Page", releaseYear: 1951 },
  { title: "On Top of Old Smoky", artist: "The Weavers", releaseYear: 1951 },
  { title: "Cold, Cold Heart", artist: "Tony Bennett", releaseYear: 1951 },
  { title: "I Get Ideas", artist: "Tony Martin", releaseYear: 1951 },
  { title: "Jealousy (Jalousie)", artist: "Frankie Laine", releaseYear: 1951 },
  { title: "Sin (It's No Sin)", artist: "Eddy Howard", releaseYear: 1951 },
  { title: "Down Yonder", artist: "Del Wood", releaseYear: 1951 },
  { title: "Sweet Violets", artist: "Dinah Shore", releaseYear: 1951 },
  { title: "Shanghai", artist: "Doris Day", releaseYear: 1951 },
  { title: "Rose, Rose, I Love You", artist: "Frankie Laine", releaseYear: 1951 },
  { title: "The Loveliest Night of the Year", artist: "Mario Lanza", releaseYear: 1951 },
  { title: "Undecided", artist: "The Ames Brothers", releaseYear: 1951 },
  { title: "Any Time", artist: "Eddie Fisher", releaseYear: 1952 },
  { title: "Here in My Heart", artist: "Al Martino", releaseYear: 1952 },
  { title: "Half as Much", artist: "Rosemary Clooney", releaseYear: 1952 },
  { title: "I Saw Mommy Kissing Santa Claus", artist: "Jimmy Boyd", releaseYear: 1952 },
  { title: "Botch-a-Me", artist: "Rosemary Clooney", releaseYear: 1952 },
  { title: "Wish You Were Here", artist: "Eddie Fisher", releaseYear: 1952 },
  { title: "Lady of Spain", artist: "Eddie Fisher", releaseYear: 1952 },
  { title: "High Noon (Do Not Forsake Me)", artist: "Frankie Laine", releaseYear: 1952 },
  { title: "Slow Poke", artist: "Pee Wee King", releaseYear: 1952 },
  { title: "Walkin' My Baby Back Home", artist: "Johnnie Ray", releaseYear: 1952 },
  { title: "Feet Up (Pat Him on the Po-Po)", artist: "Guy Mitchell", releaseYear: 1952 },
  { title: "Tell Me Why", artist: "The Four Aces", releaseYear: 1952 },
  { title: "No Other Love", artist: "Perry Como", releaseYear: 1953 },
  { title: "I'm Walking Behind You", artist: "Eddie Fisher", releaseYear: 1953 },
  { title: "Dragnet", artist: "Ray Anthony", releaseYear: 1953 },
  { title: "P.S. I Love You", artist: "The Hilltoppers", releaseYear: 1953 },
  { title: "You, You, You", artist: "The Ames Brothers", releaseYear: 1953 },
  { title: "Ricochet", artist: "Teresa Brewer", releaseYear: 1953 },
  { title: "April in Portugal", artist: "Les Baxter", releaseYear: 1953 },
  { title: "Pretend", artist: "Nat King Cole", releaseYear: 1953 },
  { title: "Eh, Cumpari!", artist: "Julius La Rosa", releaseYear: 1953 },
  { title: "Doggie in the Window", artist: "Patti Page", releaseYear: 1953 },
  { title: "The Song from Moulin Rouge", artist: "Percy Faith", releaseYear: 1953 },
  { title: "Don't Let the Stars Get in Your Eyes", artist: "Perry Como", releaseYear: 1953 },
  { title: "Wanted", artist: "Perry Como", releaseYear: 1954 },
  { title: "Little Things Mean a Lot", artist: "Kitty Kallen", releaseYear: 1954 },
  { title: "Hernando's Hideaway", artist: "Archie Bleyer", releaseYear: 1954 },
  { title: "Skokiaan", artist: "Ralph Marterie", releaseYear: 1954 },
  { title: "Hold My Hand", artist: "Don Cornell", releaseYear: 1954 },
  { title: "Papa Loves Mambo", artist: "Perry Como", releaseYear: 1954 },
  { title: "Teach Me Tonight", artist: "The DeCastro Sisters", releaseYear: 1954 },
  { title: "Cross Over the Bridge", artist: "Patti Page", releaseYear: 1954 },
  { title: "Muskrat Ramble", artist: "The McGuire Sisters", releaseYear: 1954 },
  { title: "I Need You Now", artist: "Eddie Fisher", releaseYear: 1954 },
  { title: "The High and the Mighty", artist: "Les Baxter", releaseYear: 1954 },
  { title: "Answer Me, My Love", artist: "Nat King Cole", releaseYear: 1954 },
  { title: "Cherry Pink and Apple Blossom White", artist: "Perez Prado", releaseYear: 1955 },
  { title: "The Ballad of Davy Crockett", artist: "Bill Hayes", releaseYear: 1955 },
  { title: "Dance with Me Henry", artist: "Georgia Gibbs", releaseYear: 1955 },
  { title: "Learnin' the Blues", artist: "Frank Sinatra", releaseYear: 1955 },
  { title: "Hearts of Stone", artist: "The Fontane Sisters", releaseYear: 1955 },
  { title: "Melody of Love", artist: "Billy Vaughn", releaseYear: 1955 },
  { title: "The Crazy Otto", artist: "Johnny Maddox", releaseYear: 1955 },
  { title: "Hard to Get", artist: "Gisele MacKenzie", releaseYear: 1955 },
  { title: "Something's Gotta Give", artist: "The McGuire Sisters", releaseYear: 1955 },
  { title: "Seventeen", artist: "Boyd Bennett", releaseYear: 1955 },
  { title: "Autumn Leaves", artist: "Roger Williams", releaseYear: 1955 },
  { title: "I Hear You Knocking", artist: "Gale Storm", releaseYear: 1955 },
  { title: "Lisbon Antigua", artist: "Nelson Riddle", releaseYear: 1956 },
  { title: "The Poor People of Paris", artist: "Les Baxter", releaseYear: 1956 },
  { title: "Moonglow and Theme from Picnic", artist: "Morris Stoloff", releaseYear: 1956 },
  { title: "Standing on the Corner", artist: "The Four Lads", releaseYear: 1956 },
  { title: "Hot Diggity", artist: "Perry Como", releaseYear: 1956 },
  { title: "Canadian Sunset", artist: "Hugo Winterhalter", releaseYear: 1956 },
  { title: "Tonight You Belong to Me", artist: "Patience and Prudence", releaseYear: 1956 },
  { title: "A Sweet Old Fashioned Girl", artist: "Teresa Brewer", releaseYear: 1956 },
  { title: "Ivory Tower", artist: "Cathy Carr", releaseYear: 1956 },
  { title: "More", artist: "Perry Como", releaseYear: 1956 },
  { title: "Allegheny Moon", artist: "Patti Page", releaseYear: 1956 },
  { title: "The Wayward Wind", artist: "Gogi Grant", releaseYear: 1956 },
  { title: "Singing the Blues", artist: "Guy Mitchell", releaseYear: 1956 },
  { title: "Young Love", artist: "Tab Hunter", releaseYear: 1957 },
  { title: "Love Letters in the Sand", artist: "Pat Boone", releaseYear: 1957 },
  { title: "Tammy", artist: "Debbie Reynolds", releaseYear: 1957 },
  { title: "Honeycomb", artist: "Jimmie Rodgers", releaseYear: 1957 },
  { title: "Chances Are", artist: "Johnny Mathis", releaseYear: 1957 },
  { title: "All Shook Up", artist: "Elvis Presley", releaseYear: 1957 },
  { title: "Too Much", artist: "Elvis Presley", releaseYear: 1957 },
  { title: "Round and Round", artist: "Perry Como", releaseYear: 1957 },
  { title: "A White Sport Coat", artist: "Marty Robbins", releaseYear: 1957 },
  { title: "It's Not for Me to Say", artist: "Johnny Mathis", releaseYear: 1957 },
  { title: "Old Cape Cod", artist: "Patti Page", releaseYear: 1957 },
  { title: "Fascination", artist: "Jane Morgan", releaseYear: 1957 },
  { title: "April Love", artist: "Pat Boone", releaseYear: 1957 },
  { title: "Raunchy", artist: "Bill Justis", releaseYear: 1957 },
  { title: "My Special Angel", artist: "Bobby Helms", releaseYear: 1957 },
  { title: "Mona Lisa", artist: "Gordon Jenkins", releaseYear: 1950 },
  { title: "The Thing", artist: "Arthur Godfrey", releaseYear: 1950 },
  { title: "Patricia", artist: "Perry Como", releaseYear: 1950 },
  { title: "If", artist: "Perry Como", releaseYear: 1951 },
  { title: "Aba Daba Honeymoon", artist: "Debbie Reynolds and Carleton Carpenter", releaseYear: 1951 },
  { title: "The World Is Waiting for the Sunrise", artist: "Les Paul and Mary Ford", releaseYear: 1951 },
  { title: "My Truly, Truly Fair", artist: "Guy Mitchell", releaseYear: 1951 },
  { title: "Because of You", artist: "Mario Lanza", releaseYear: 1951 },
  { title: "Shrimp Boats", artist: "The Du Droppers", releaseYear: 1951 },
  { title: "Blue Velvet", artist: "Tony Bennett", releaseYear: 1951 },
  { title: "The Blacksmith Blues", artist: "Ella Mae Morse", releaseYear: 1952 },
  { title: "You Belong to Me", artist: "Patti Page", releaseYear: 1952 },
  { title: "Auf Wiederseh'n Sweetheart", artist: "Vera Lynn", releaseYear: 1952 },
  { title: "Kiss of Fire", artist: "Georgia Gibbs", releaseYear: 1952 },
  { title: "Till I Waltz Again with You", artist: "Teresa Brewer", releaseYear: 1952 },
  { title: "I Went to Your Wedding", artist: "Patti Page", releaseYear: 1952 },
  { title: "Why Don't You Believe Me", artist: "Joni James", releaseYear: 1952 },
  { title: "Rags to Riches", artist: "Billy Ward and His Dominoes", releaseYear: 1953 },
  { title: "Vaya Con Dios", artist: "Les Paul and Mary Ford", releaseYear: 1953 },
  { title: "Changing Partners", artist: "Patti Page", releaseYear: 1953 },
  { title: "Stranger in Paradise", artist: "Tony Bennett", releaseYear: 1953 },
  { title: "The Moon Is Blue", artist: "The Marcels", releaseYear: 1953 },
  { title: "C'est Magnifique", artist: "Gordon MacRae", releaseYear: 1953 },
  { title: "This Ole House", artist: "Rosemary Clooney", releaseYear: 1954 },
  { title: "Hey There", artist: "Rosemary Clooney", releaseYear: 1954 },
  { title: "Make Love to Me", artist: "Jo Stafford", releaseYear: 1954 },
  { title: "Sincerely", artist: "The Moonglows", releaseYear: 1954 },
  { title: "Mr. Sandman", artist: "The Chordettes", releaseYear: 1954 },
  { title: "Sh-Boom", artist: "The Chords", releaseYear: 1954 },
  { title: "The Little Shoemaker", artist: "The Gaylords", releaseYear: 1954 },
  { title: "Let Me Go, Devil", artist: "Doris Day", releaseYear: 1954 },
  { title: "A Blossom Fell", artist: "Nat King Cole", releaseYear: 1955 },
  { title: "The Yellow Rose of Texas", artist: "Mitch Miller", releaseYear: 1955 },
  { title: "Love Is a Many-Splendored Thing", artist: "The Four Aces", releaseYear: 1955 },
  { title: "At My Front Door", artist: "The El Dorados", releaseYear: 1955 },
  { title: "Ain't That a Shame", artist: "Pat Boone", releaseYear: 1955 },
  { title: "Unchained Melody", artist: "Al Hibbler", releaseYear: 1955 },
  { title: "Memories Are Made of This", artist: "Dean Martin", releaseYear: 1955 },
  { title: "Sixteen Tons", artist: "Tennessee Ernie Ford", releaseYear: 1955 },
  { title: "Blue Suede Shoes", artist: "Elvis Presley", releaseYear: 1956 },
  { title: "My Prayer", artist: "The Platters", releaseYear: 1956 },
  { title: "Since I Don't Have You", artist: "The Skyliners", releaseYear: 1959 },
  { title: "I'm Walkin'", artist: "Fats Domino", releaseYear: 1957 },
  { title: "Blueberry Hill", artist: "Fats Domino", releaseYear: 1956 },
  { title: "A Teenager's Romance", artist: "Ricky Nelson", releaseYear: 1957 },
  { title: "You Send Me", artist: "Sam Cooke", releaseYear: 1957 },
  { title: "Little Darlin'", artist: "The Diamonds", releaseYear: 1957 },
  { title: "Silhouettes", artist: "The Rays", releaseYear: 1957 },
  { title: "Come Go with Me", artist: "The Del-Vikings", releaseYear: 1957 },
  { title: "School Days", artist: "Chuck Berry", releaseYear: 1957 },
  { title: "The Stroll", artist: "The Diamonds", releaseYear: 1957 },
  { title: "Butterfly", artist: "Andy Williams", releaseYear: 1957 },
  { title: "Kisses Sweeter Than Wine", artist: "The Weavers", releaseYear: 1951 },
  { title: "A Guy Is a Guy", artist: "Doris Day", releaseYear: 1952 },
  { title: "Secret Love", artist: "Doris Day", releaseYear: 1953 },
  { title: "Love and Marriage", artist: "Frank Sinatra", releaseYear: 1955 },
  { title: "The Great Pretender", artist: "The Platters", releaseYear: 1955 },
  { title: "Why Do Fools Fall in Love", artist: "Frankie Lymon & The Teenagers", releaseYear: 1956 },
  { title: "Fever", artist: "Little Willie John", releaseYear: 1956 },
  { title: "The Tennessee Waltz", artist: "Patti Page", releaseYear: 1950 },
  { title: "Mister Sandman", artist: "The Chordettes", releaseYear: 1954 },
  { title: "Nature Boy", artist: "Nat King Cole", releaseYear: 1950 },
  { title: "Mambo Italiano", artist: "Rosemary Clooney", releaseYear: 1954 },
  { title: "How Much Is That Doggie in the Window?", artist: "Patti Page", releaseYear: 1953 },
  { title: "The Thing", artist: "Phil Harris", releaseYear: 1950 },
  { title: "Mockin' Bird Hill", artist: "Les Paul and Mary Ford", releaseYear: 1951 },
  { title: "Auf Wiederseh'n Sweetheart", artist: "Vera Lynn", releaseYear: 1952 },
  { title: "The Hot Canary", artist: "Florian ZaBach", releaseYear: 1951 },
  { title: "Kiss of Fire", artist: "Georgia Gibbs", releaseYear: 1952 },
  { title: "Till I Waltz Again with You", artist: "Teresa Brewer", releaseYear: 1952 },
  { title: "Changing Partners", artist: "Patti Page", releaseYear: 1953 },
  { title: "Secret Love", artist: "Doris Day", releaseYear: 1953 },
  { title: "Make Love to Me", artist: "Jo Stafford", releaseYear: 1954 },
  { title: "Hey There", artist: "Rosemary Clooney", releaseYear: 1954 },
  { title: "Sincerely", artist: "The Moonglows", releaseYear: 1954 },
  { title: "The Yellow Rose of Texas", artist: "Mitch Miller", releaseYear: 1955 },
  { title: "Unchained Melody", artist: "Al Hibbler", releaseYear: 1955 },
  { title: "A Blossom Fell", artist: "Nat King Cole", releaseYear: 1955 },
  { title: "Love Is a Many-Splendored Thing", artist: "The Four Aces", releaseYear: 1955 },
  { title: "At My Front Door", artist: "The El Dorados", releaseYear: 1955 },
  { title: "Rip It Up", artist: "Little Richard", releaseYear: 1956 },
  { title: "I'm Walkin'", artist: "Fats Domino", releaseYear: 1957 },
  { title: "Blueberry Hill", artist: "Fats Domino", releaseYear: 1956 },
  { title: "A Teenager's Romance", artist: "Ricky Nelson", releaseYear: 1957 },
  { title: "You Send Me", artist: "Sam Cooke", releaseYear: 1957 },
  { title: "Little Darlin'", artist: "The Diamonds", releaseYear: 1957 },
  { title: "Silhouettes", artist: "The Rays", releaseYear: 1957 },
  { title: "Come Go with Me", artist: "The Del-Vikings", releaseYear: 1957 },
  { title: "School Days", artist: "Chuck Berry", releaseYear: 1957 },
  { title: "The Stroll", artist: "The Diamonds", releaseYear: 1957 },
  { title: "Butterfly", artist: "Andy Williams", releaseYear: 1957 },
  { title: "Mona Lisa", artist: "Nat King Cole", releaseYear: 1950 },
  { title: "Goodnight, Irene", artist: "The Weavers", releaseYear: 1950 },
  { title: "If", artist: "Perry Como", releaseYear: 1950 },
  { title: "Be My Love", artist: "Mario Lanza", releaseYear: 1950 },
  { title: "Harbor Lights", artist: "Sammy Kaye", releaseYear: 1950 },
  { title: "Because of You", artist: "Tony Bennett", releaseYear: 1951 },
  { title: "Too Young", artist: "Nat King Cole", releaseYear: 1951 },
  { title: "Come On-a My House", artist: "Rosemary Clooney", releaseYear: 1951 },
  { title: "Unforgettable", artist: "Nat King Cole", releaseYear: 1951 },
  { title: "How High the Moon", artist: "Les Paul and Mary Ford", releaseYear: 1951 },
  { title: "Cry", artist: "Johnnie Ray", releaseYear: 1951 },
  { title: "Wheel of Fortune", artist: "Kay Starr", releaseYear: 1952 },
  { title: "Why Don't You Believe Me", artist: "Joni James", releaseYear: 1952 },
  { title: "You Belong to Me", artist: "Jo Stafford", releaseYear: 1952 },
  { title: "A Guy Is a Guy", artist: "Doris Day", releaseYear: 1952 },
  { title: "Jambalaya (On the Bayou)", artist: "Hank Williams", releaseYear: 1952 },
  { title: "That Doggie in the Window", artist: "Patti Page", releaseYear: 1953 },
  { title: "Vaya Con Dios", artist: "Les Paul and Mary Ford", releaseYear: 1953 },
  { title: "Rags to Riches", artist: "Tony Bennett", releaseYear: 1953 },
  { title: "Ebb Tide", artist: "Frank Chacksfield", releaseYear: 1953 },
  { title: "Three Coins in the Fountain", artist: "The Four Aces", releaseYear: 1954 },
  { title: "This Ole House", artist: "Rosemary Clooney", releaseYear: 1954 },
  { title: "Mr. Sandman", artist: "The Chordettes", releaseYear: 1954 },
  { title: "Earth Angel", artist: "The Penguins", releaseYear: 1954 },
  { title: "Sh-Boom", artist: "The Chords", releaseYear: 1954 },
  { title: "The Little Shoemaker", artist: "The Gaylords", releaseYear: 1954 },
  { title: "Rock Around the Clock", artist: "Bill Haley & His Comets", releaseYear: 1955 },
  { title: "Tutti Frutti", artist: "Little Richard", releaseYear: 1955 },
  { title: "Maybellene", artist: "Chuck Berry", releaseYear: 1955 },
  { title: "Ain't That a Shame", artist: "Fats Domino", releaseYear: 1955 },
  { title: "Sixteen Tons", artist: "Tennessee Ernie Ford", releaseYear: 1955 },
  { title: "Love and Marriage", artist: "Frank Sinatra", releaseYear: 1955 },
  { title: "Only You (And You Alone)", artist: "The Platters", releaseYear: 1955 },
  { title: "Blue Suede Shoes", artist: "Carl Perkins", releaseYear: 1956 },
  { title: "Hound Dog", artist: "Elvis Presley", releaseYear: 1956 },
  { title: "Heartbreak Hotel", artist: "Elvis Presley", releaseYear: 1956 },
  { title: "Long Tall Sally", artist: "Little Richard", releaseYear: 1956 },
  { title: "Que Sera, Sera (Whatever Will Be, Will Be)", artist: "Doris Day", releaseYear: 1956 },
  { title: "The Great Pretender", artist: "The Platters", releaseYear: 1956 },
  { title: "Why Do Fools Fall in Love", artist: "Frankie Lymon & The Teenagers", releaseYear: 1956 },
  { title: "Fever", artist: "Little Willie John", releaseYear: 1956 },
  { title: "Peggy Sue", artist: "Buddy Holly", releaseYear: 1957 },
  { title: "That'll Be the Day", artist: "The Crickets", releaseYear: 1957 },
  { title: "Jailhouse Rock", artist: "Elvis Presley", releaseYear: 1957 },
  { title: "Great Balls of Fire", artist: "Jerry Lee Lewis", releaseYear: 1957 },
  { title: "Whole Lotta Shakin' Goin' On", artist: "Jerry Lee Lewis", releaseYear: 1957 },
  { title: "Wake Up Little Susie", artist: "The Everly Brothers", releaseYear: 1957 },
  { title: "Diana", artist: "Paul Anka", releaseYear: 1957 },
  { title: "Short Shorts", artist: "The Royal Teens", releaseYear: 1957 },
];
